name: Generate capabilities and config schema

on:
  push:
    branches:
      - main

jobs:
  generate_outputs:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build connector
        run: go build -o connector ./cmd/baton-salesforce

      - name: Run and save config output
        run: ./connector config > config_schema.json

      - name: Run and save capabilities output
        run: ./connector capabilities > baton_capabilities.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updating baton config schema and capabilities."
          add: |
            config_schema.json
            baton_capabilities.json 