name: ci
on: pull_request
jobs:
  test-grant-user:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
      BATON_SALESFORCE_CLIENT_ID: ${{ secrets.SALESFORCE_CLIENT_ID }}
      BATON_SALESFORCE_CLIENT_SECRET: ${{ secrets.SALESFORCE_CLIENT_SECRET }}
      BATON_AUTH_METHOD: client-credentials-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-salesforce
        run: go build ./cmd/baton-salesforce
      - name: Test grant/revoking IAM entitlements
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-salesforce
          baton-entitlement: ${{ vars.BATON_ENTITLEMENT_GROUP }}
          baton-principal: ${{ vars.BATON_PRINCIPAL_USER }}
          baton-principal-type: user
  test-grant-permission-set-group:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
      BATON_SALESFORCE_CLIENT_ID: ${{ secrets.SALESFORCE_CLIENT_ID }}
      BATON_SALESFORCE_CLIENT_SECRET: ${{ secrets.SALESFORCE_CLIENT_SECRET }}
      BATON_AUTH_METHOD: client-credentials-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-salesforce
        run: go build ./cmd/baton-salesforce
      - name: Test grant/revoking IAM entitlements
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-salesforce
          baton-entitlement: ${{ vars.BATON_ENTITLEMENT_PSG }}
          baton-principal: ${{ vars.BATON_PRINCIPAL_USER }}
          baton-principal-type: user
  test-grant-territory:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_INSTANCE_URL: ${{ secrets.INSTANCE_URL }}
      BATON_SALESFORCE_CLIENT_ID: ${{ secrets.SALESFORCE_CLIENT_ID }}
      BATON_SALESFORCE_CLIENT_SECRET: ${{ secrets.SALESFORCE_CLIENT_SECRET }}
      BATON_AUTH_METHOD: client-credentials-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-salesforce
        run: go build ./cmd/baton-salesforce
      - name: Test grant/revoking territory entitlements
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-salesforce
          baton-entitlement: ${{ vars.BATON_ENTITLEMENT_TERRITORY }}
          baton-principal: ${{ vars.BATON_PRINCIPAL_USER }}
          baton-principal-type: user
